### ISSUE TITLE
Are username and password really needed?

### ISSUE THREAD

**Issue by winstliu** [magalhas/atom-jenkins#1]
I just tried accessing my Jenkins server's [cc.xml](http://198.27.69.149/jenkins/cc.xml) on a totally new profile of Chrome and I have no issues connecting to it.  Is there any reason why a password is specifically needed (and not hidden in Settings)?

**Comment by magalhas** [comment]
I think it depends on your Jenkins settings. If you have tight security settings, cc.xml won't be accesible afaik.

**Comment by winstliu** [comment]
:/.
Can we then have the option of not entering the user/password if our Jenkins doesn't need it?  Currently it won't even try accessing Jenkins without the username and password.

**Comment by magalhas** [comment]
It makes sense. Feel free to do a PR or I’ll work on it when I find the time.

Best regards,José Magalhães

**Comment by magalhas** [comment]
#9 clears this out. This can be closed as of now.
