### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by daithi-coombes** [magalhas/atom-jenkins#3]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:54:11)
JenkinsView.initialize (/home/daithi/.atom/packages/jenkins/lib/jenkins-view.coffee:23:9)
```

**Comment by magalhas** [comment]
Just fixed the deprecation notices. Thank you for reporting :+1:
